/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as kastjTreasurySol from './KastjTreasury.sol/index.js';
export * as interfaces from './interfaces/index.js';
export * as mocks from './mocks/index.js';
export { EscrowVault__factory } from './EscrowVault__factory.js';
export { ProposalManager__factory } from './ProposalManager__factory.js';