/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface EscrowVaultInterface extends Interface {
    getFunction(nameOrSignature: "BPS_DENOMINATOR" | "CREATOR_REWARD_BPS" | "PLATFORM_FEE_BPS" | "depositKrc20" | "depositNative" | "deposits" | "enableWithdrawals" | "manager" | "owner" | "proposalBalances" | "proposalRegistered" | "proposalToken" | "registerProposal" | "releaseSuccess" | "released" | "setManager" | "withdraw" | "withdrawMany" | "withdrawalsEnabled"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Deposited" | "ManagerSet" | "ProposalRegistered" | "Released" | "WithdrawalsEnabled" | "Withdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'BPS_DENOMINATOR', values?: undefined): string;
encodeFunctionData(functionFragment: 'CREATOR_REWARD_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'PLATFORM_FEE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'depositKrc20', values: [BigNumberish, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'depositNative', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'deposits', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'enableWithdrawals', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'manager', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposalBalances', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'proposalRegistered', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'proposalToken', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'registerProposal', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'releaseSuccess', values: [BigNumberish, AddressLike, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'released', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setManager', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawMany', values: [BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'withdrawalsEnabled', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'BPS_DENOMINATOR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'CREATOR_REWARD_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PLATFORM_FEE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositKrc20', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositNative', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'enableWithdrawals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'manager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposalBalances', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposalRegistered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposalToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseSuccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'released', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setManager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawMany', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawalsEnabled', data: BytesLike): Result;
  }

  
    export namespace DepositedEvent {
      export type InputTuple = [proposalId: BigNumberish, supporter: AddressLike, token: AddressLike, amount: BigNumberish];
      export type OutputTuple = [proposalId: bigint, supporter: string, token: string, amount: bigint];
      export interface OutputObject {proposalId: bigint, supporter: string, token: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ManagerSetEvent {
      export type InputTuple = [manager: AddressLike];
      export type OutputTuple = [manager: string];
      export interface OutputObject {manager: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalRegisteredEvent {
      export type InputTuple = [proposalId: BigNumberish, token: AddressLike];
      export type OutputTuple = [proposalId: bigint, token: string];
      export interface OutputObject {proposalId: bigint, token: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReleasedEvent {
      export type InputTuple = [proposalId: BigNumberish, token: AddressLike, recipient: AddressLike, creator: AddressLike, treasury: AddressLike, recipientPayout: BigNumberish, creatorReward: BigNumberish, platformFee: BigNumberish];
      export type OutputTuple = [proposalId: bigint, token: string, recipient: string, creator: string, treasury: string, recipientPayout: bigint, creatorReward: bigint, platformFee: bigint];
      export interface OutputObject {proposalId: bigint, token: string, recipient: string, creator: string, treasury: string, recipientPayout: bigint, creatorReward: bigint, platformFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawalsEnabledEvent {
      export type InputTuple = [proposalId: BigNumberish];
      export type OutputTuple = [proposalId: bigint];
      export interface OutputObject {proposalId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawnEvent {
      export type InputTuple = [proposalId: BigNumberish, supporter: AddressLike, token: AddressLike, amount: BigNumberish];
      export type OutputTuple = [proposalId: bigint, supporter: string, token: string, amount: bigint];
      export interface OutputObject {proposalId: bigint, supporter: string, token: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface EscrowVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): EscrowVault;
    waitForDeployment(): Promise<this>;

    interface: EscrowVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BPS_DENOMINATOR: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    CREATOR_REWARD_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PLATFORM_FEE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    depositKrc20: TypedContractMethod<
      [proposalId: BigNumberish, supporter: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    depositNative: TypedContractMethod<
      [proposalId: BigNumberish, supporter: AddressLike, ],
      [void],
      'payable'
    >
    

    
    deposits: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [[bigint, boolean] & {amount: bigint, withdrawn: boolean }],
      'view'
    >
    

    
    enableWithdrawals: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    manager: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    proposalBalances: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    proposalRegistered: TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    proposalToken: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    registerProposal: TypedContractMethod<
      [proposalId: BigNumberish, token: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    releaseSuccess: TypedContractMethod<
      [proposalId: BigNumberish, recipient: AddressLike, creator: AddressLike, treasury: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    released: TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    setManager: TypedContractMethod<
      [_manager: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawMany: TypedContractMethod<
      [proposalIds: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    withdrawalsEnabled: TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BPS_DENOMINATOR'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'CREATOR_REWARD_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PLATFORM_FEE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'depositKrc20'): TypedContractMethod<
      [proposalId: BigNumberish, supporter: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'depositNative'): TypedContractMethod<
      [proposalId: BigNumberish, supporter: AddressLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'deposits'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [[bigint, boolean] & {amount: bigint, withdrawn: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'enableWithdrawals'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'manager'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proposalBalances'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'proposalRegistered'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'proposalToken'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerProposal'): TypedContractMethod<
      [proposalId: BigNumberish, token: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releaseSuccess'): TypedContractMethod<
      [proposalId: BigNumberish, recipient: AddressLike, creator: AddressLike, treasury: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'released'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'setManager'): TypedContractMethod<
      [_manager: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawMany'): TypedContractMethod<
      [proposalIds: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawalsEnabled'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'Deposited'): TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
getEvent(key: 'ManagerSet'): TypedContractEvent<ManagerSetEvent.InputTuple, ManagerSetEvent.OutputTuple, ManagerSetEvent.OutputObject>;
getEvent(key: 'ProposalRegistered'): TypedContractEvent<ProposalRegisteredEvent.InputTuple, ProposalRegisteredEvent.OutputTuple, ProposalRegisteredEvent.OutputObject>;
getEvent(key: 'Released'): TypedContractEvent<ReleasedEvent.InputTuple, ReleasedEvent.OutputTuple, ReleasedEvent.OutputObject>;
getEvent(key: 'WithdrawalsEnabled'): TypedContractEvent<WithdrawalsEnabledEvent.InputTuple, WithdrawalsEnabledEvent.OutputTuple, WithdrawalsEnabledEvent.OutputObject>;
getEvent(key: 'Withdrawn'): TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;

    filters: {
      
      'Deposited(uint256,address,address,uint256)': TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
      Deposited: TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
    

      'ManagerSet(address)': TypedContractEvent<ManagerSetEvent.InputTuple, ManagerSetEvent.OutputTuple, ManagerSetEvent.OutputObject>;
      ManagerSet: TypedContractEvent<ManagerSetEvent.InputTuple, ManagerSetEvent.OutputTuple, ManagerSetEvent.OutputObject>;
    

      'ProposalRegistered(uint256,address)': TypedContractEvent<ProposalRegisteredEvent.InputTuple, ProposalRegisteredEvent.OutputTuple, ProposalRegisteredEvent.OutputObject>;
      ProposalRegistered: TypedContractEvent<ProposalRegisteredEvent.InputTuple, ProposalRegisteredEvent.OutputTuple, ProposalRegisteredEvent.OutputObject>;
    

      'Released(uint256,address,address,address,address,uint256,uint256,uint256)': TypedContractEvent<ReleasedEvent.InputTuple, ReleasedEvent.OutputTuple, ReleasedEvent.OutputObject>;
      Released: TypedContractEvent<ReleasedEvent.InputTuple, ReleasedEvent.OutputTuple, ReleasedEvent.OutputObject>;
    

      'WithdrawalsEnabled(uint256)': TypedContractEvent<WithdrawalsEnabledEvent.InputTuple, WithdrawalsEnabledEvent.OutputTuple, WithdrawalsEnabledEvent.OutputObject>;
      WithdrawalsEnabled: TypedContractEvent<WithdrawalsEnabledEvent.InputTuple, WithdrawalsEnabledEvent.OutputTuple, WithdrawalsEnabledEvent.OutputObject>;
    

      'Withdrawn(uint256,address,address,uint256)': TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
      Withdrawn: TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
    
    };
  }