/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'EscrowVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.EscrowVault__factory>
getContractFactory(name: 'IKRC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IKRC20__factory>
getContractFactory(name: 'IERC20Like', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC20Like__factory>
getContractFactory(name: 'KastjTreasury', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.KastjTreasury__factory>
getContractFactory(name: 'MockKRC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockKRC20__factory>
getContractFactory(name: 'ProposalManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ProposalManager__factory>

  getContractAt(name: 'EscrowVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.EscrowVault>
getContractAt(name: 'IKRC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IKRC20>
getContractAt(name: 'IERC20Like', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC20Like>
getContractAt(name: 'KastjTreasury', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.KastjTreasury>
getContractAt(name: 'MockKRC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockKRC20>
getContractAt(name: 'ProposalManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ProposalManager>

  deployContract(name: 'EscrowVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EscrowVault>
deployContract(name: 'IKRC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKRC20>
deployContract(name: 'IERC20Like', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20Like>
deployContract(name: 'KastjTreasury', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KastjTreasury>
deployContract(name: 'MockKRC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockKRC20>
deployContract(name: 'ProposalManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ProposalManager>

  deployContract(name: 'EscrowVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EscrowVault>
deployContract(name: 'IKRC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKRC20>
deployContract(name: 'IERC20Like', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20Like>
deployContract(name: 'KastjTreasury', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KastjTreasury>
deployContract(name: 'MockKRC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockKRC20>
deployContract(name: 'ProposalManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ProposalManager>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  