/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ProposalManager {
      
    export type ProposalStruct = {id: BigNumberish, creator: AddressLike, recipient: AddressLike, token: AddressLike, goalAmount: BigNumberish, minThreshold: BigNumberish, deadline: BigNumberish, totalRaised: BigNumberish, status: BigNumberish, settlementMode: BigNumberish, finalized: boolean, metadataURI: string}

    export type ProposalStructOutput = [id: bigint, creator: string, recipient: string, token: string, goalAmount: bigint, minThreshold: bigint, deadline: bigint, totalRaised: bigint, status: bigint, settlementMode: bigint, finalized: boolean, metadataURI: string] & {id: bigint, creator: string, recipient: string, token: string, goalAmount: bigint, minThreshold: bigint, deadline: bigint, totalRaised: bigint, status: bigint, settlementMode: bigint, finalized: boolean, metadataURI: string }
  
    }

  export interface ProposalManagerInterface extends Interface {
    getFunction(nameOrSignature: "createProposal" | "finalizeProposal" | "fundKrc20" | "fundNative" | "getProposal" | "owner" | "proposalCount" | "proposals" | "setTokenDecimals" | "setTreasury" | "tokenDecimals" | "treasury" | "vault"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ProposalCreated" | "ProposalFinalized" | "ProposalFunded"): EventFragment;

    encodeFunctionData(functionFragment: 'createProposal', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'finalizeProposal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'fundKrc20', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'fundNative', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProposal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposalCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposals', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTokenDecimals', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTreasury', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'tokenDecimals', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'vault', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'createProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundKrc20', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundNative', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposalCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTokenDecimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenDecimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vault', data: BytesLike): Result;
  }

  
    export namespace ProposalCreatedEvent {
      export type InputTuple = [proposalId: BigNumberish, creator: AddressLike, recipient: AddressLike, token: AddressLike, goalAmount: BigNumberish, minThreshold: BigNumberish, deadline: BigNumberish, settlementMode: BigNumberish, metadataURI: string];
      export type OutputTuple = [proposalId: bigint, creator: string, recipient: string, token: string, goalAmount: bigint, minThreshold: bigint, deadline: bigint, settlementMode: bigint, metadataURI: string];
      export interface OutputObject {proposalId: bigint, creator: string, recipient: string, token: string, goalAmount: bigint, minThreshold: bigint, deadline: bigint, settlementMode: bigint, metadataURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalFinalizedEvent {
      export type InputTuple = [proposalId: BigNumberish, status: BigNumberish, totalRaised: BigNumberish];
      export type OutputTuple = [proposalId: bigint, status: bigint, totalRaised: bigint];
      export interface OutputObject {proposalId: bigint, status: bigint, totalRaised: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalFundedEvent {
      export type InputTuple = [proposalId: BigNumberish, supporter: AddressLike, token: AddressLike, amount: BigNumberish, totalRaised: BigNumberish];
      export type OutputTuple = [proposalId: bigint, supporter: string, token: string, amount: bigint, totalRaised: bigint];
      export interface OutputObject {proposalId: bigint, supporter: string, token: string, amount: bigint, totalRaised: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ProposalManager extends BaseContract {
    
    connect(runner?: ContractRunner | null): ProposalManager;
    waitForDeployment(): Promise<this>;

    interface: ProposalManagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createProposal: TypedContractMethod<
      [recipient: AddressLike, token: AddressLike, goalAmount: BigNumberish, minThreshold: BigNumberish, durationSeconds: BigNumberish, settlementMode: BigNumberish, metadataURI: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    finalizeProposal: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    fundKrc20: TypedContractMethod<
      [proposalId: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    fundNative: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    getProposal: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [ProposalManager.ProposalStructOutput],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    proposalCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    proposals: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, bigint, bigint, bigint, boolean, string] & {id: bigint, creator: string, recipient: string, token: string, goalAmount: bigint, minThreshold: bigint, deadline: bigint, totalRaised: bigint, status: bigint, settlementMode: bigint, finalized: boolean, metadataURI: string }],
      'view'
    >
    

    
    setTokenDecimals: TypedContractMethod<
      [token: AddressLike, decimals: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTreasury: TypedContractMethod<
      [_treasury: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    tokenDecimals: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    vault: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createProposal'): TypedContractMethod<
      [recipient: AddressLike, token: AddressLike, goalAmount: BigNumberish, minThreshold: BigNumberish, durationSeconds: BigNumberish, settlementMode: BigNumberish, metadataURI: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'finalizeProposal'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fundKrc20'): TypedContractMethod<
      [proposalId: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fundNative'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'getProposal'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [ProposalManager.ProposalStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proposalCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'proposals'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, bigint, bigint, bigint, boolean, string] & {id: bigint, creator: string, recipient: string, token: string, goalAmount: bigint, minThreshold: bigint, deadline: bigint, totalRaised: bigint, status: bigint, settlementMode: bigint, finalized: boolean, metadataURI: string }],
      'view'
    >;
getFunction(nameOrSignature: 'setTokenDecimals'): TypedContractMethod<
      [token: AddressLike, decimals: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTreasury'): TypedContractMethod<
      [_treasury: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tokenDecimals'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'vault'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'ProposalCreated'): TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
getEvent(key: 'ProposalFinalized'): TypedContractEvent<ProposalFinalizedEvent.InputTuple, ProposalFinalizedEvent.OutputTuple, ProposalFinalizedEvent.OutputObject>;
getEvent(key: 'ProposalFunded'): TypedContractEvent<ProposalFundedEvent.InputTuple, ProposalFundedEvent.OutputTuple, ProposalFundedEvent.OutputObject>;

    filters: {
      
      'ProposalCreated(uint256,address,address,address,uint256,uint256,uint256,uint8,string)': TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
      ProposalCreated: TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
    

      'ProposalFinalized(uint256,uint8,uint256)': TypedContractEvent<ProposalFinalizedEvent.InputTuple, ProposalFinalizedEvent.OutputTuple, ProposalFinalizedEvent.OutputObject>;
      ProposalFinalized: TypedContractEvent<ProposalFinalizedEvent.InputTuple, ProposalFinalizedEvent.OutputTuple, ProposalFinalizedEvent.OutputObject>;
    

      'ProposalFunded(uint256,address,address,uint256,uint256)': TypedContractEvent<ProposalFundedEvent.InputTuple, ProposalFundedEvent.OutputTuple, ProposalFundedEvent.OutputObject>;
      ProposalFunded: TypedContractEvent<ProposalFundedEvent.InputTuple, ProposalFundedEvent.OutputTuple, ProposalFundedEvent.OutputObject>;
    
    };
  }