/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20Like__factory } from './IERC20Like__factory.js';
export { KastjTreasury__factory } from './KastjTreasury__factory.js';