import { keccak256, toUtf8Bytes } from "ethers";
import type { ProposalMessageType, ProposalMessageAuthorRole } from "./ProposalMessage";

export const MAX_PROPOSAL_MESSAGE_LENGTH = 2000;

/**
 * Normalizes message body by trimming and collapsing whitespace.
 * This ensures consistent hashing for vProgs.
 */
export function normalizeProposalMessageBody(body: string): string {
  return body.trim().replace(/\s+/g, " ");
}

/**
 * Generates a keccak256 hash of the normalized message body.
 * This hash can be used as a commitment in future vProgs/ZK proofs.
 */
export function hashProposalMessageBody(body: string): string {
  const normalized = normalizeProposalMessageBody(body);
  return keccak256(toUtf8Bytes(normalized));
}

/**
 * Validates the message body length and content.
 */
export function validateProposalMessageBody(body: string): string {
  const normalized = normalizeProposalMessageBody(body);

  if (!normalized) {
    throw new Error("Message body cannot be empty");
  }

  if (normalized.length > MAX_PROPOSAL_MESSAGE_LENGTH) {
    throw new Error(`Message body cannot exceed ${MAX_PROPOSAL_MESSAGE_LENGTH} characters`);
  }

  return normalized;
}

/**
 * Validates if the author role is allowed to send the specified message type.
 */
export function validateProposalMessageType(
  type: ProposalMessageType,
  authorRole: ProposalMessageAuthorRole
): ProposalMessageType {
  if (type === "system") {
    throw new Error("System messages can only be generated by the platform");
  }

  if (type === "update" || type === "answer") {
    if (authorRole !== "creator" && authorRole !== "moderator") {
      throw new Error(`Only the creator or a moderator can post an ${type}`);
    }
  }

  return type;
}
